[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AQvPyINy-PFMjmlNsQWodPOqQv5ZpGqKbeq9_g-B6qTRN4LEF5mhLlWj6eTeL-q0KESvbRHprM1ePIj-0vyp0v1qvsKSEqI5d5vtgev059i4HOlT0OHi2uCWgMn5_Opqd1kG9AUFrj5BxR2qG5UgKpoR1irzVuxVm8wgU9Yi3MgYnHKOv3vN-3ONXwPfz6cKrUVDAkgaCgYKAZ0SARQSFQHGX2MijdzzAVF3dWNakQkoUjY1Eg0206","token_type":"Bearer","refresh_token":"1//03tuSfM4n5OiNCgYIARAAGAMSNwF-L9IrrAuYB4kdf2ICRiMBMMyaZMK0zNqlGCAi4fHUwnL5Ix7CFilZ9eE3j1HzoVOQyGa9eUM","expiry":"2026-06-02T18:56:21.0224758+03:00","expires_in":3599}
