[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AT3oNZ_mG2eHBT4ZWvjdsU7lrRHUdvrfVWucInlUolpAtESNtTDewCrXun64Fs8HHfuYxNXKOAz9QTTN_x3aKSsm1xjJVm9UTM9p8ZOrpUEVTDKnVJ7_UCovUPSeSAdyInBy-lbJiqqLkelF3x70iQQd0xiA2c1UbNv2kp0DErKUKFea9ayzrFHUxQUKnIdz-Il4kWtO-gaCgYKAQUSARQSFQHGX2MiXOE5P2b30cGv2aI9zSoRNg0209","token_type":"Bearer","refresh_token":"1//03tuSfM4n5OiNCgYIARAAGAMSNwF-L9IrrAuYB4kdf2ICRiMBMMyaZMK0zNqlGCAi4fHUwnL5Ix7CFilZ9eE3j1HzoVOQyGa9eUM","expiry":"2026-06-29T05:32:43.931307599Z","expires_in":3599}

