[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AT3oNZ-xG1A-MqwiMof3NBsvDdup7Yk3vn5L-PL_PNKFyUuKk2TxLdiEKH59nQO6-mMbO9l8tVV0xOOdcx9OCsWOccszSxCXNyasQMAqnPGMEvF8jo0OVkfdiwlQPfbfbZCzPJgcDVC-HnIuKXKcKHGVEAFiYoT_BDUdk3Frg7rqThXz5UdoELWsMCKy5DqNhO1qfPJwaCgYKAesSARQSFQHGX2MiVPNoWOYt36AbWweoCHtpaQ0207","token_type":"Bearer","refresh_token":"1//03tuSfM4n5OiNCgYIARAAGAMSNwF-L9IrrAuYB4kdf2ICRiMBMMyaZMK0zNqlGCAi4fHUwnL5Ix7CFilZ9eE3j1HzoVOQyGa9eUM","expiry":"2026-06-09T05:05:59.713937296Z","expires_in":3599}

